version: '3.8'

services:
  app:
    build: .
    container_name: vms-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${PORT}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - WS_PORT=${WS_PORT}
    restart: always